include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - always_declare_return_types
    - avoid_print
    - avoid_unnecessary_containers
    - prefer_single_quotes
